CREATE TABLE IF NOT EXISTS APP_USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    total_rentals INT DEFAULT 0,
    has_missed_film BOOLEAN DEFAULT FALSE,
    credit DECIMAL(19, 2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS FILM (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS RENTAL (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    film_id BIGINT,
    rental_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    cost DECIMAL(19, 2) NOT NULL,
    deposit DECIMAL(19, 2) NOT NULL,
    is_late BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES APP_USER (id),
    CONSTRAINT fk_film FOREIGN KEY (film_id) REFERENCES FILM(id)
);